name: releasing new version

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Run a multi-line script
        run: |
          # saving the build ip address in to a variable
          pwd
          ls
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $LAST_TAG
