name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]
env:
  tag_prefix: test
  tag_main_version: 0
  tag_sub_version: 0
jobs:
  release:
    runs-on: Ubuntu-20.04

    steps:
      - name: "get a new tag"
        run: |
          git config --global user.email "me@erme2.com"
          git config --global user.name "erme2"
          git clone https://erme2:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git tmp
          cd tmp
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          lastNumber=$(echo $latestTag |cut -d'.' -f3)
          newNumber=$(expr $lastNumber + 1)
          zero="0"
          new_minor=$TAG_MAIN_VERSION.$TAG_SUB_VERSION.
          size=${#newNumber}
          stop=$(($TAG_LAST_NUMBER_LENGTH-1))
          while [ $size -le $stop ] \ do \ new_minor="$new_minor$zero" \ size=$(( $size + 1 )) \ done
          tag_new="$tag_prefix-$tag_main_version.$tag_sub_version."
          echo tag_new: $tag_new
          echo new_minor: $new_minor
          cd ..
          rm -rf tmp
