name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]

jobs:
  release:
    runs-on: Ubuntu-20.04

    steps:
      - name: "get a new tag"
        env:
          prefix: test
          main_version: 0
          sub_version: 0
        run: |
          new_tag="$prefix-$main_version.$sub_version.$GITHUB_RUN_ID.$GITHUB_RUN_NUMBER"
          echo $new_tag
#  run_tests:
#    runs-on: Ubuntu-20.04
#
#    steps:
#      - name: just some test code
#        run: echo OK!

