name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "test-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Some other step # Output usage example
        with:
        run: echo ${{ steps.tagName.outputs.tag }}
#
#      - uses: actions/checkout@v2
#      - name: 'Get Previous tag'
#        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

