name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: retrieve branch version
    steps:
      - uses: actions/checkout@v2
      - id: version-retriever
        uses: CarterChen247/version-retriever@v1
      - name: echo retrieved version
        run: echo retrieved version => ${{ steps.version-retriever.outputs.version }}
        shell: bash
