name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]
env:
  tag_prefix: test
  tag_main_version: 0
  tag_sub_version: 0
jobs:
  release:
    runs-on: Ubuntu-20.04

    steps:
      - name: "get a new tag"
        run: |
          tag_new="$tag_prefix-$tag_main_version.$tag_sub_version.$GITHUB_RUN_NUMBER"
          echo $tag_new
          echo $GITHUB_RUN_NUMBER
          echo Repo: $GITHUB_REPOSITORY
          git clone https://erme2:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git tmp
          cd tmp
          ls
          pwd
#          ${{ secrets.GITHUB_TOKEN }}
