name: running tests on all brances

on:
  push:
    branches: [ ]
    branches-ignore: [ master ]

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - name: Run a multi-line script
        run: |
          # saving the build ip address in to a variable
          MY_IP_ADDRESS=$(dig +short myip.opendns.com @resolver1.opendns.com)
          echo $MY_IP_ADDRESS
