name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: 'Get Previous tag'
        run: echo "${GITHUB_REF##*/}"
