name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]

jobs:
  release:
    runs-on: Ubuntu-20.04

    steps:
      - name: "get a new tag"
        env:
          prefix: test
          main_version: 0
          sub_version: 0
        run: |
          new_tag="$prefix-$main_version.$sub_version.$GITHUB_RUN_NUMBER"
          echo $new_tag
          echo $GITHUB_RUN_NUMBER
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ new_tag }}
          release_name: Release ${{ github.ref }}
          body: |
            echo $new_tag
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

#  run_tests:
#    runs-on: Ubuntu-20.04
#
#    steps:
#      - name: just some test code
#        run: echo OK!

