name: running tests on all brances

on:
  push:
    branches-ignore: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: retrieve branch version
    steps:
      - uses: actions/get_last_tag@main
      - name: 'Get Previous tag'
        run: sh get_last_tag.sh
